added frontend url's and created the new config file as region wise

diff --git a/flutter/TDS-fluttersprint b/flutter/TDS-fluttersprint
--- a/flutter/TDS-fluttersprint
+++ b/flutter/TDS-fluttersprint
@@ -1,44 +1,122 @@
+import groovy.transform.Field
+
+@Field def ARR_VERIFY_SERVICE = []
+@Field def IS_WEBAPPS_ENABLED
+
+
+def webapps = [
+    [key: 'TDS']
+]
+def checkoutProject(String projectName, String branch) {
+    sh "mkdir -p ${projectName}"
+    dir("${projectName}") {
+        checkout([$class: 'GitSCM', 
+            branches: [[name: branch]], 
+            doGenerateSubmoduleConfigurations: false, 
+            extensions: [[$class: 'CleanCheckout']], 
+            userRemoteConfigs: [[url: "https://github.com/Bottle-Lab-Technologies-PVT-LTD/${projectName}.git", credentialsId: 'git/devops/new']]])
+
+        sh 'ls -lrt'
+        def commitId = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
+        echo "Commit ID: ${commitId}"
+        newId = commitId
+    }
+}
+
+properties([
+    parameters([
+        [$class: 'ChoiceParameter',
+            choiceType: 'PT_SINGLE_SELECT',
+            description: 'Select Branch Name',
+            filterLength: 1,
+            filterable: false,
+            name: 'BRANCH_NAME',
+            script: [
+                $class: 'GroovyScript',
+                fallbackScript: [
+                    classpath: [],
+                    sandbox: true,
+                    script: 'return ["auto-sprint", "auto-release", "hotfix"]'
+                ],
+                script: [
+                    classpath: [],
+                    sandbox: true,
+                    script: '''
+                        def choices = ["auto-sprint", "auto-release", "hotfix"]
+                        return choices
+                    '''
+                ]
+            ] 
+        ],
+        string(name: 'GIT_BRANCH',defaultValue: '', description: 'hotfix branch name'),
+        string(name: 'COMMIT_ID',defaultValue: '', description: 'Enter commit_id'),
+        [$class: 'ChoiceParameter',
+            choiceType: 'PT_CHECKBOX',
+            description: 'Select Project Name',
+            filterLength: 1,
+            filterable: false,
+            name: 'PROJECT_NAME',
+            script: [
+                $class: 'GroovyScript',
+                fallbackScript: [
+                    classpath: [],
+                    sandbox: true,
+                    script: 'return ["TDS:selected"]'
+                ],
+                script: [
+                    classpath: [],
+                    sandbox: true,
+                    script: '''
+                        def choices = ["TDS:selected"]
+                        return choices
+                    '''
+                ]
+            ] 
+        ]
+    ])
+])
+
 pipeline {
     agent {
         kubernetes {
-            label 'flutter-test'
             defaultContainer 'jnlp'
             yaml '''
-        apiVersion: v1
-        kind: Pod
-        spec:
-          containers:
-          - name: gcloud
-            image: google/cloud-sdk:latest
-            command:
-                - sleep
-            args:
-                - 99d
-            tty: true
-                
-          - name: flutter
-            image: mingc/android-build-box:master
-            resources:
-              requests:
-                memory: "4096Mi"  # Increase the requested memory
-                cpu: "500m"
-              limits:
-                memory: "8192Mi"  # Increase the maximum allowed memory
-                cpu: "1000m"
-            command:
-            - sh
-            args:
-            - -c
-            - |
-              set -e  # Exit immediately if a command exits with a non-zero status
-              apt-get update && \
-              apt-get install -y wget && \
-              wget https://services.gradle.org/distributions/gradle-8.7-all.zip && \
-			  unzip gradle-8.7-all.zip && \
-              ls -l && \
-              sleep 99d
-            tty: true
-        '''        
+            apiVersion: v1
+            kind: Pod
+            environment:
+                name: "NODE_OPTIONS"
+                value: "--max-old-space-size=4096"
+            spec:
+              containers:
+              - name: tds-flutter
+                image: mingc/android-build-box:master
+                resources:
+                requests:
+                    memory: "4096Mi"  # Increase the requested memory
+                    cpu: "500m"
+                limits:
+                    memory: "8192Mi"  # Increase the maximum allowed memory
+                    cpu: "1000m"
+                command:
+                - sh
+                args:
+                - -c
+                - |
+                  set -e  # Exit immediately if a command exits with a non-zero status
+                  apt-get update && \
+                  apt-get install -y wget && \
+                  wget https://services.gradle.org/distributions/gradle-8.7-all.zip && \
+                  unzip gradle-8.7-all.zip && \
+                  ls -l && \
+                  sleep 99d
+                  tty: true
+
+              - name: gcloud
+                image: google/cloud-sdk:latest
+                command:
+                - cat
+                tty: true
+            '''        
         }
     }
     environment {
@@ -47,24 +125,66 @@ pipeline {
         KEYSTORE_PASSWORD = 'Smartq@123'
         KEY_PASSWORD = 'Smartq@123'
     }
-
     stages {
-        stage('Checkout flutter') { 
-            steps { 
-                sh "mkdir -p tds-flutter"
-                dir('tds-flutter') {
-                    git branch: 'auto-sprint',
-                    credentialsId: 'git/devops/new',
-                    url: 'https://github.com/Bottle-Lab-Technologies-PVT-LTD/TDS.git'
-                    sh 'ls'
+        stage('checking project'){
+            steps{
+                script{
+                    //mail_url = 'https://cpgplc.webhook.office.com/webhookb2/6d5ff299-54f8-4bb3-911b-4ef2d419e335@cd62b7dd-4b48-44bd-90e7-e143a22c8ead/IncomingWebhook/3b95c290077440da9d684a0c498039e1/1b69cb54-bc9e-4431-98fa-5afcb910e9d4'
+
+                    if(params.PROJECT_NAME == "All" || params.PROJECT_NAME.isEmpty()){
+                        def options = 'TDS'
+                        ARR_SELECTED_SERVICE = "$options".split(',')
+                    }
+                    else {
+                        ARR_SELECTED_SERVICE = params.PROJECT_NAME.split(',')
+                    }
+                    echo "Selected Services - $ARR_SELECTED_SERVICE"
+
+                    IS_WEBAPPS_ENABLED = ARR_SELECTED_SERVICE.any { element -> webapps.key.contains(element) }
+                    echo "IS_WEBAPPS_ENABLED - $IS_WEBAPPS_ENABLED"
+                }                
+            }
+        }
+        stage('checkout stage'){
+            steps {
+                script {
+                    //def bitBucketProject = params.BitBucketProject.toLowerCase()
+                    def branch = params.BRANCH_NAME
+                    def hotfixbranch = params.GIT_BRANCH //whenever we spcify hotfix parameter please provied commitId parameter because project is pulling from commitid not hotfixbranch
+                    def commitid = params.COMMIT_ID
+                    //def bucketname = params.Branch
+                    echo "selcted branch = ${branch}"
+                    echo "selcted hotfixbranch = ${hotfixbranch}"
+                    echo "selcted commitid = ${commitid}"
+                    if (GIT_BRANCH != '') {
+                    	//bucketname="${hotfixbranch}"
+                    	branch="${hotfixbranch}"
+                    } else if (COMMIT_ID != ''){
+                    	branch="${commitid}"                    	
+                    } else {
+                        branch = params.BRANCH_NAME
+                    }
+                    
+                    if (COMMIT_ID != '' && GIT_BRANCH != ''){
+                        branch="${commitId}"
+                    }
+                    def parallelJobs = [:]
+                    ARR_SELECTED_SERVICE.each { service ->
+                        parallelJobs["Checkout ${service}"] = {
+                            if (service in ['IMD-flutter']) {
+                                checkoutProject(service, branch)
+                            }
+                        }    
+                    }
+                    parallel(parallelJobs)
                 }
-            }                       
+            }
         }
         stage('Build tds-flutter') {
             steps {
-                container('flutter') {
+                container('tds-flutter') {
                     withCredentials([file(credentialsId: 'TDS.jks', variable: 'KEYSTORE_PATH')]) {
-                        dir('tds-flutter') {
+                        dir('TDS') {
                             sh """
                             echo "storePassword=${KEYSTORE_PASSWORD}" > android/key.properties
                             echo "keyPassword=${KEY_PASSWORD}" >> android/key.properties
@@ -79,7 +199,7 @@ pipeline {
                                 sh 'echo changing to directory'
                                 dir('app') {
                                     sh 'ls'
-                                    dir('outputs/flutter-apk') {
+                                    dir('outputs/apk/release') {
                                         sh 'ls -lrt'
                                     }
                                 }
@@ -89,24 +209,39 @@ pipeline {
                 }             
             }       
         }
-        stage('copy apk file'){
+        stage('copy to GCS') {
             steps {
-                container('gcloud'){
-                    dir('tds-flutter'){
-                        dir ('${WORKSPACE}/build') {                            
-                        sh 'echo changing to directory'
-                            dir('app'){
-                                dir('outputs/flutter-apk'){
-                                    sh 'ls -lrt'
-                                    sh "mv app-release.apk TDS.apk"
-                                    sh "mv app-release.apk.sha1 TDS.apk.sha1"
-                                    sh 'gcloud storage cp * gs://smartqdemo_pub/ --recursive'
+                script {
+                    container('gcloud') {
+                        if ('IMD-flutter' in ARR_SELECTED_SERVICE) {
+                            dir('IMD-flutter') {
+                                dir ('${WORKSPACE}/build') {
+                                    sh 'echo changing to directory'
+                                    dir('app') {
+                                        sh 'ls'
+                                        dir('outputs/apk/release'){
+                                            sh 'ls -lrt'
+                                            sh "rm output-metadata.json"
+                                            //sh "mv app-release.apk IMD.apk"
+                                            //sh "mv app-release.apk.sha1 IMD.apk.sha1"
+                                            sh "gcloud storage cp * gs://sqinternational-cicd.appspot.com/Global_Region/${branch}/TDS/ --recursive"
+                                        }
+                                    }
                                 }
-                            }
-                        }
+                            }    
+                        } 
                     }
                 }
             }
         }
     }
+    // post{
+    //     always{
+    //         script {
+    //             office365ConnectorSend webhookUrl: "${mail_url}",
+    //             message : "Build is running.\nJob Name: ${Job_Name}.\nBuild Status: ${currentBuild.currentResult}.\nJenkins Build Number: ${Build_Number}.\nApplication  Name: ${projectName}.\nGCP Cloud URL: ${CLOUD_URL}.\n Version Number: ${VERSION_NUMBER} ",
+    //             status: "Build Status# ${currentBuild.currentResult}"
+    //         }
+    //     }
+    // }
 }
